name: Slack Notifications

on:
  pull_request:
    branches: [ main ]

jobs:
  notifySlack:

    runs-on: ubuntu-latest

    steps:
    - name: Notify Slack
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        curl -X POST -H 'Content-type: application/json' --data '{
          "channel": "C0892210G3A",
          "blocks": [
            {
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "*Pull Request:* ${{ github.event.pull_request.title }}"
              }
            },
            {
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "*Who?:* ${{ github.event.pull_request.user.login }}\n*Request State:* ${{ github.event.pull_request.state }}"
              }
            },
            {
              "type": "actions",
              "elements": [
                {
                  "type": "button",
                  "text": {
                    "type": "plain_text",
                    "text": "Approve"
                  },
                  "style": "primary",
                  "url": "${{ github.event.pull_request.html_url }}"
                },
                {
                  "type": "button",
                  "text": {
                    "type": "plain_text",
                    "text": "Reject"
                  },
                  "style": "danger",
                  "url": "${{ github.event.pull_request.html_url }}"
                },
                {
                  "type": "button",
                  "text": {
                    "type": "plain_text",
                    "text": "View Pull Request"
                  },
                  "url": "${{ github.event.pull_request.html_url }}",
                  "style": "primary"
                }
              ]
            }
          ]
        }' $SLACK_WEBHOOK_URL
