name: Slack Notifications

on:
  pull_request:
    branches: [ master ]

jobs:
  notifySlack:
    runs-on: ubuntu-latest

    steps:
      - name: Send Slack Notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*Pull Request:* ${{ github.event.pull_request.title }}"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*Who?:* ${{ github.event.pull_request.user.login }}\n*State:* ${{ github.event.pull_request.state }}"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "<${{ github.event.pull_request.html_url }}|View Pull Request>"
                }
              }
            ]
          }' $SLACK_WEBHOOK_URL
